app/app/urls.py
from datetime import datetime
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from authentication import forms, views
from authentication import views as viewHome
from workOrder import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/',views.simple_upload),
    path('upload_payroll/',views.upload_payroll),
    path('order_list/',views.listOrders),
    path('order_detail/<id>/<isSupervisor>',views.order_detail ),
    path('order_list_location/<str:userID>',views.order_list_location),
    path('order_list_sup/',views.order_list_sup),
    path('create_order/',views.create_order),
    path('order/<str:orderID>',views.order),
    path('order_supervisor/<str:orderID>',views.order_supervisor),
    path('truncateData/',views.truncateData),
    path('updateDupOrder/<str:pID>/<str:dupID>',views.updateDupOrder),
    path('insertDupOrder/<str:dupID>',views.insertDupOrder),
    path('deleteDupOrder/<str:pID>',views.deleteDupOrder),
    path('duplicate_order_list/',views.duplicatelistOrders),
    path('checkOrder/<str:pID>',views.checkOrder),
    path('location/',views.create_location),
    path('location_list/',views.location_list),
    path('update_location/<id>',views.update_location),
    path('employee_list/',views.employee_list),
    path('create_employee/',views.create_employee),
    path('update_employee/<id>',views.update_employee),
    path('link_order_list/<id>',views.linkOrderList),
    path('link_order/<id>/<manualid>',views.linkOrder),
    path('updateLinkOrder/<id>/<manualid>',views.updateLinkOrder),
    path('item_list/',views.item_list),
    path('create_item/',views.create_item),
    path('update_item/<id>',views.update_item),
    path('item_price/<id>',views.item_price),
    path('create_item_price/<id>',views.create_item_price),
    path('update_item_price/<id>',views.update_item_price),
    path('po_list/<id>',views.po_list),
    path('internal_po_list/',views.internal_po_list),
    path('get_internal_po_list/<estatus>/<poNumber>/<pid>',views.get_internal_po_list),
    path('update_po/<id>/<woID>/<selectedvs>',views.update_po),
    path('unlink_po/<id>/<woID>',views.unlink_po),
    path('delete_po/<id>/<woID>',views.delete_po),
    path('create_po/<id>/<selectedvs>',views.create_po),
    path('add_internalPO_to_estimate/<poID>/<woID>/<estimateID>',views.add_internalPO_to_estimate),
    path('add_hours_to_estimate/<woID>/<estimateID>',views.add_hours_to_estimate),
    path('estimate_preview/<id>/<estimateID>',views.estimate_preview),
    path('download_estimate_preview/<id>/<estimateID>',views.download_estimate_preview),
    path('partial_estimate/<id>/<isPartial>/<Status>/<addressID>',views.partial_estimate),
    path('invoice_preview/<id>/<invoiceID>',views.invoice_preview),
    path('estimate/<id>/<estimateID>',views.estimate),
    path('invoice/<id>/<invoiceID>',views.invoice),
    path('upload_item/',views.upload_item),
    path('upload_item_price/',views.upload_item_price),
    path('upload_employees/',views.upload_employee),
    path('period_list/',views.period_list),
    path('location_period_list/<id>',views.location_period_list),    
    path('orders_payroll/<dailyID>/<LocID>',views.orders_payroll, name="orders_payroll"),   
    path('vendor_subcontractor_list/<woID>/<tipoOp>/<id>',views.vendor_subcontractor_list),  
    path('payroll/<perID>/<dID>/<crewID>/<LocID>',views.payroll),
    path('payroll_audit/<id>',views.payroll_audit),
    path('payroll_audit_delete/<perID>/<LocID>/<dID>',views.payroll_audit_delete),
    path('update_order_daily/<woID>/<dailyID>/<LocID>',views.update_order_daily),
    path('create_daily/<pID>/<dID>/<LocID>',views.create_daily),
    path('update_daily/<daily>',views.update_daily),
    path('create_daily_emp/<id>/<LocID>',views.create_daily_emp),
    path('update_daily_emp/<id>/<LocID>',views.update_daily_emp),
    path('delete_daily_emp/<id>/<LocID>',views.delete_daily_emp),
    path('create_daily_item/<id>/<LocID>',views.create_daily_item),
    path('update_daily_item/<id>/<LocID>',views.update_daily_item),
    path('delete_daily_item/<id>/<LocID>',views.delete_daily_item),
    path('upload_daily/<id>/<LocID>',views.upload_daily),
    path('recap/<perID>',views.recap),
    path('send_recap/<perID>',views.send_recap),
    path('send_recap_emp/<perID>/<empID>',views.send_recap_emp),
    path('get_summary/<perID>',views.get_summary),
    path('update_sup_daily/<id>/<woid>',views.update_sup_daily),
    path('delete_daily/<id>/<LocID>',views.delete_daily),
    path('status_log/<id>/<isSupervisor>',views.status_log),
    path('supervisor_approval/<id>',views.supervisor_appoval),
    path('close_payroll/<id>',views.close_payroll),
    path('payroll_detail/<id>',views.payroll_detail),
    path('get_order_list/<estatus>/<loc>/<pid>/<addR>/<invNumber>/<invAmount>/<invAmountF>/<superV>',views.get_order_list),
    path('get_emp_list/',views.get_emp_list),
    path('get_item_list/',views.get_item_list),
    path('vendor_list/',views.vendor_list),
    path('create_vendor/',views.create_vendor),
    path('create_vendor_modal/<woID>/<tipoOP>/<poID>',views.create_vendor_modal),
    path('update_vendor/<id>',views.update_vendor),
    path('subcontractor_list/',views.subcontractor_list),
    path('create_subcontractor/',views.create_subcontractor),
    path('create_subcontractor_modal/<woID>/<tipoOP>/<poID>',views.create_subcontractor_modal),
    path('update_subcontractor/<id>',views.update_subcontractor),
    path('external_prod_list/<id>',views.external_prod_list),
    path('create_external_prod/<woID>',views.create_external_prod),
    path('get_external_prod/<id>',views.get_external_prod),
    path('update_external_prod/<id>',views.update_external_prod),
    path('upload_external_prod/<id>',views.upload_external_prod),
    path('create_ext_prod_item/<id>',views.create_ext_prod_item),
    path('update_ext_prod_item/<id>',views.update_ext_prod_item),
    path('delete_ext_prod_item/<id>',views.delete_ext_prod_item),
    path('authorized_billing_list/<id>',views.authorized_billing_list),
    path('create_authorized_prod_item/<id>/<invoiceID>/<estimateID>',views.create_authorized_prod_item),
    path('update_authorized_prod_item/<id>/<invoiceID>/<estimateID>',views.update_authorized_prod_item),
    path('delete_authorized_prod_item/<id>/<invoiceID>/<estimateID>',views.delete_authorized_prod_item),
    path('delete_hours/<orderID>/<invoiceID>/<estimateID>',views.delete_hours),
    path('comment_authorized_prod_item/<id>',views.comment_authorized_prod_item),
    path('billing_list/<id>/<isRestoring>',views.billing_list),
    path('restore_original_production/<id>',views.restore_original_production),
    path('update_invoice/<id>/<invoiceID>',views.update_invoice),
    path('update_estimate/<id>/<estimateID>',views.update_estimate),
    path('employee_location_list/<empID>',views.employee_location_list),
    path('create_employee_location/<empID>',views.create_employee_location),
    path('delete_employee_location/<empID>',views.delete_employee_location),
    path('pending_internal_po/<id>/<isPartial>/<isUpdate>',views.pending_internal_po),
    path('select_billing_address/<id>/<isPartial>/<isUpdate>',views.select_billing_address),
    path('billing_address_list/',views.billing_address_list),
    path('create_billing_address/',views.create_billing_address),
    path('update_billing_address/<id>',views.update_billing_address),
    path('production_transfer/<id>/<invoiceID>/<estimateID>',views.production_transfer),
    path('internal_po_transfer/<id>/<invoiceID>/<estimateID>',views.internal_po_transfer),
    path('invoice_daily_report/',views.invoice_daily_report),
    path('invoice_monthly_report/',views.invoice_monthly_report),
    path('payroll_employee_report/<empID>/',views.payroll_employee_report),
    path('get_summary_by_employee/<dateSelected>/<dateSelected2>/<empID>/<LocationID>/<Tipo>', views.get_summary_by_employee),
    path('employee_list_pay_report/',views.employee_list_pay_report),  
    path('get_daily_report/<dateSelected>',views.get_daily_report),
    path('get_monthly_report/<dateSelected>/<dateSelected2>/<status>',views.get_monthly_report),
    path('wo_balance_Report/',views.wo_balance_Report),
    path('get_balance_report/<status>/<location>', views.get_balance_report),
    path('wo_comment_log/<woID>/<isSupervisor>',views.wo_comment_log),
    path('get_wo_comment_log/<id>',views.get_wo_comment_log),
    #Temp URL's
    path('update_linked_orders/',views.update_linked_orders),
    path('update_pending_invoice/',views.update_pending_invoice),
    path('update_item_payout/',views.update_item_payout),
    path('update_emp_payout/',views.update_emp_payout),
    path('update_estimate_address/<woID>/<addressID>/<estimateID>',views.update_estimate_address),
    path('wo_adjustment/<woID>/<estimateID>',views.wo_adjustment),
    path('update_wo_adjustment/<woID>/<estimateID>',views.update_wo_adjustment),
    path('list_linked_orders/',views.list_linked_orders),
    path('update_total_invoice/',views.update_total_invoice),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),
    path('', include('authentication.urls')),
    path('login_audit/',views.login_audit),
    path('home/', include('authentication.urls')),
    path('',
         LoginView.as_view
         (
             template_name='login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context={
                 'title': 'Log in',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
         path('login/',viewHome.login),
         # Timesheet URLs
        path('timesheet/', include('timesheet.urls')), 
    ]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,

app/timesheet/urls.py
from turtle import home
from django.contrib import admin
from django.urls import path, include
from . import views
from timesheet import views

urlpatterns = [
     path('employee_list/',views.employee_list),   
     path('employee_submitted_list/',views.employee_submitted_list), 
     path('create/',views.create),
     path('update/<id>',views.update),
     path('create/',views.create),
     # ****** Supervisor **********************
     path('supervisor_list/',views.supervisor_list), 
     path('create_by_supervisor/',views.createBySupervisor),
     path('update_by_super/<id>',views.updateBySuper),
     path('update_status/<id>/<status>',views.update_status),
     path('reject_timesheet/<id>',views.reject_timesheet),
     path('approve_timesheet/<id>',views.approve_timesheet),
     # ****** Reports **********************
     path('report_list/',views.report_list), 
     path('get_report_list/<dateSelected>/<dateSelected2>/<status>/<location>/<employee>/<type>',views.get_report_list),
]

app/timesheet/models.py
from contextlib import nullcontext
from operator import truediv
from pyexpat import model
from random import choices
from statistics import mode
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime
from workOrder import models as catalogModel

prodStatus_choice = (
    (1, 'Draft'),
    (2, 'Sent'),
    (3, 'Pending'),
    (4, 'Approved'),
    (5, 'Rejected')
)

class Timesheet(models.Model):
    EmployeeID = models.ForeignKey(catalogModel.Employee, on_delete=models.CASCADE, db_column ='EmployeeID', null=False, blank=False)
    date = models.DateField(null=False, blank=False)
    start_time = models.IntegerField(null=True, blank=True)
    start_lunch_time = models.IntegerField(null=True, blank=True)
    end_lunch_time = models.IntegerField(null=True, blank=True)
    end_time = models.IntegerField(null=True, blank=True)
    total_hours = models.FloatField(null=True, blank=True)
    regular_hours = models.FloatField(null=True, blank=True)
    ot_hour = models.FloatField(null=True, blank=True)
    double_time = models.FloatField(null=True, blank=True)
    start_mileage = models.IntegerField(null=True, blank=True)
    end_mileage = models.IntegerField(null=True, blank=True)
    total_mileage = models.IntegerField(null=True, blank=True)
    Status = models.IntegerField(default=1, choices = prodStatus_choice)   
    Location = models.ForeignKey(catalogModel.Locations, on_delete=models.CASCADE, db_column ='Location', null=False, blank=False)  
    comments = models.CharField(max_length=200, blank=True, null=True)
    created_date = models.DateTimeField(null=True, blank=True)
    createdBy = models.CharField(max_length=60, blank=True, null=True)
    updated_date = models.DateTimeField(null=True, blank=True)
    updatedBy = models.CharField(max_length=60, blank=True, null=True)
    Period = models.ForeignKey(catalogModel.period, on_delete=models.CASCADE, db_column ='Period', null=True, blank=True)
    crew = models.ForeignKey(catalogModel.Daily, on_delete=models.CASCADE, db_column ='crew', null=True, blank=True)
    #crew = models.IntegerField(null=True, blank=True)
    transferred_date = models.DateTimeField(null=True, blank=True)
    tranferredBy = models.CharField(max_length=60, blank=True, null=True)
    

    def __str__(self):
        return  str(self.date)
    
    class Meta:
        unique_together = ('EmployeeID','date')
    #COnsultar cuantas veces puede enviar el empleado información al dia

app/templates/timesheet/approve_timesheet.html
{% extends 'base_modal.html' %} 
{%load static%}
{% block title %} Order List {% endblock %} 
{% load humanize %}
{% block container %}
{% load widget_tweaks%}

<div class="container">
    <form method='post' action="{{request.path}}" class="modal-content" id="rejectedTimseheet">
        {% csrf_token %}

        <div class="modal-header">
            <h5>Approve Timesheet</h5>           
        </div>              
       
        <div class="modal-body">  
            <div class="row mb-2">
                <div class="col-lg-8">
                    <span class="">
                        <strong>Are you sure to Approve and Move to Production this Timesheet?</strong>
                    </span>
                </div>
            </div>           
            <div class="row">
                <div class="col-lg-12">
                    <div class="mb3-mobile">
                        <label for="{{ form.EmployeeID.id_for_label }}" class="form-label">Employee</label>
                        {% render_field form.EmployeeID  name="date" id="date" class="form-control" %}
                        <div class="invalid-feedback">{{ form.EmployeeID.errors|first }}</div>
                    </div>    
                </div>                    
            </div>   
            <div class="row"> 
                
                <div class="col-sm-5">               
                    <div class="mb3-mobile">
                        <label for="{{ form.Period.id_for_label }}" class="form-label">Period</label>
                        {% render_field form.Period name="Period" id="Period" class="form-control" %}
                        <div class="invalid-feedback">{{ form.Period.errors|first }}</div>
                    </div>    
                </div>
                      
                <div class="col-sm-5">               
                    <div class="mb3-mobile">
                        <label for="{{ form.date.id_for_label }}" class="form-label">Date</label>
                        {% render_field form.date type="date" name="date" id="date" class="form-control" %}
                        <div class="invalid-feedback">{{ form.date.errors|first }}</div>
                    </div>    
                </div>
                <div class="col-lg-2">
                    <div class="mb3-mobile">
                        <label for="{{ form.crew.id_for_label }}" class="form-label">Crew</label>
                        {% render_field form.crew  name="crew" id="crew" class="form-control" %}
                        <div class="invalid-feedback">{{ form.crew.errors|first }}</div>
                    </div>    
                </div>     
            </div>  
            <div class="row">
                <div class="col-lg-12">

                    <div class="mb3-mobile">
                        <label for="{{ form.comments.id_for_label }}" class="form-label">Comments</label>
                        {% render_field form.comments|attr:"rows:5"|attr:"cols:20"|attr:"required:required" class="form-control" %}
                        <div class="invalid-feedback">{{ form.date.errors|first }}</div>
                    </div>    
                
                </div>
            </div>
        </div>

        
        
        <div class="modal-footer">   
            <input class="btn btn-primary" type="submit" value="Save">       
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button> 
        </div>
   
    </form>
</div>
{% endblock %}

app/templates/timesheet/supervisor_list.html
{% extends 'index.html' %}
{%load static%}

{% block container %}

<script src="{% static 'js/supervisor.js' %}"></script>

<div class="container">
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            <div class="col-sm-10 my-3"></div>

        </div>


        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <h6 class="card-header card-header-wc">Filters</h6>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-2">
                                <div class="mb-3">
                                    <label for="PID" class="form-label">Status</label>
                                    <div class="input-group mb-3">

                                        <select class="form-select" aria-label="Default select example" name="status"
                                            id="status">

                                            {%if selectEstatus == "0"%}
                                            <option value="0" selected>Status</option>
                                            {%else%}
                                            <option value="0">Status</option>
                                            {%endif%}

                                            {%if selectEstatus == "2"%}
                                            <option value="2" selected>Sent</option>
                                            {%else%}
                                            <option value="2">Sent</option>
                                            {%endif%}
                                            {%if selectEstatus == "3"%}
                                            <option value="3" selected>Pending</option>
                                            {%else%}
                                            <option value="3">Pending</option>
                                            {%endif%}
                                            {%if selectEstatus == "4"%}
                                            <option value="4" selected>Approved</option>
                                            {%else%}
                                            <option value="4">Approved</option>
                                            {%endif%}
                                            {%if selectEstatus == "5"%}
                                            <option value="5" selected>Rejected</option>
                                            {%else%}
                                            <option value="5">Rejected</option>
                                            {%endif%}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="mb-3">
                                    <label for="PID" class="form-label">Select Date From</label>
                                    <div class="input-group mb-3">
                                        <input type="date" name="date" placeholder="mm-dd-yyyy" value=""
                                            min="1997-01-01" max="2030-12-31" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="mb-3">
                                    <label for="PID" class="form-label">To</label>
                                    <div class="input-group mb-3">
                                        <input type="date" name="date2" placeholder="mm-dd-yyyy" value=""
                                            min="1997-01-01" max="2030-12-31" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <label for="PID" class="form-label">Location</label>
                                <div class="input-group mb-3">
                                    <select class="form-select" aria-label="Select Location" name="location"
                                        id="location">

                                        {%if selectLoc == "0" %}
                                        <option value="0" selected>Select a Location</option>
                                        {%else%}
                                        <option value="0">Select a Location</option>
                                        {%endif%}
                                        {% for data in location %}
                                        {%if data.LocationID|slugify == selectLoc%}
                                        <option value="{{data.LocationID}}" selected>{{data.name}}</option>
                                        {%else%}
                                        <option value="{{data.LocationID}}">{{data.name}}</option>
                                        {%endif%}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <label for="PID" class="form-label">Employee</label>
                                <div class="input-group mb-3">
                                    <select class="form-select" aria-label="Select Employee" name="emp" id="emp">

                                        {%if selectEmployee == "0" %}
                                        <option value="0" selected>Select a Employee</option>
                                        {%else%}
                                        <option value="0">Select a Employee</option>
                                        {%endif%}
                                        {% for data in empList %}
                                        {%if data.employeeID|slugify == selectEmployee%}
                                        <option value="{{data.employeeID}}" selected>{{data.first_name}}
                                            {{data.last_name}} </option>
                                        {%else%}
                                        <option value="{{data.employeeID}}">{{data.first_name}} {{data.last_name}}
                                        </option>
                                        {%endif%}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-1 my-4">
                                <input class="btn btn-primary" type="submit" value="Search">
                            </div>
                            <div class="col-sm-2 my-4">
                                <a class="btn btn-success" href="/timesheet/create_by_supervisor/" role="button">New</a>
                                <a href="/home/" type="button" class="btn btn-danger">Close</a>
                            </div>




                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 my-3">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-9">
                                <h6 class="">Timesheet List </h6>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-12">
                            <table id="orders" class="table table-sm table-bordered table-striped">
                                <thead class="table-primary">
                                    <tr>
                                        <th scope="col" style="width: 6%">Date</th>
                                        <th scope="col" style="width: 10%">Name</th>
                                        <th scope="col" style="width: 10%">Location</th>
                                        <th scope="col" style="width: 5%">Clock In</th>
                                        <th scope="col" style="width: 5%">Lunch Start</th>
                                        <th scope="col" style="width: 5%">Lunch End</th>
                                        <th scope="col" style="width: 5%">Clock Out</th>
                                        <th scope="col" style="width: 5%">Hours worked</th>
                                        <th scope="col" style="width: 6%">Starting Mileage</th>
                                        <th scope="col" style="width: 6%">Ending Mileage</th>
                                        <th scope="col" style="width: 6%">Total Mileage</th>
                                        <th scope="col" style="width: 4%">Status</th>
                                        <th scope="col" style="width: 4%">Updated By</th>
                                        <th scope="col" style="width: 5%"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for data in dataset %}
                                    <tr>
                                        <td>{{data.date|date:'Y-m-d'}}</td>
                                        <td>{{data.EmployeeID}}</td>
                                        <td>{{data.Location}}</td>
                                        <td>{{data.start_time}}</td>
                                        <td>{{data.start_lunch_time}}</td>
                                        <td>{{data.end_lunch_time}}</td>
                                        <td>{{data.end_time}}</td>
                                        <td>{{data.total_hours}}</td>
                                        <td>{{data.start_mileage}}</td>
                                        <td>{{data.end_mileage}}</td>
                                        <td>{{data.total_mileage}}</td>

                                        <td>{{data.get_Status_display}}</td>

                                        <td>{{data.updatedBy}}</td>
                                        <td class="text-justify">
                                            {% if data.Status == 2%}
                                            <!--<a href="/timesheet/update_status/{{data.id}}/5" data-bs-toggle="tooltip" data-bs-placement="top" title="Reject"><i class="fa-solid fa-x mr-1" style="color: red;"></i></a>-->

                                            <!-- <a href=""
                                                onClick="ApproveReject(this, 4,{{data.id}}, 'Are you sure to Approve this Timesheet')"
                                                data-bs-toggle="tooltip" data-bs-placement="top" title="Approve"><i
                                                    class="fa-solid fa-check mr-1" style="color: green;"></i></a>-->
                                                <a hx-get="/timesheet/approve_timesheet/{{data.id}}" hx-target="#dialog"><i
                                                    class="fa-solid fa-check mr-1" style="color: green;"></i></a>
                                                            
                                                <a hx-get="/timesheet/reject_timesheet/{{data.id}}" hx-target="#dialog"><i
                                                        class="fa-solid fa-x mr-1" style="color: red;"></i></a>
                                            <!--<a href="" onClick="ApproveReject(this, 5,{{data.id}}, 'Are you sure to Reject this Timesheet')" data-bs-toggle="tooltip" data-bs-placement="top" title="Reject"><i class="fa-solid fa-x mr-1" style="color: red;"></i></a>-->
                                            {%endif%}
                                            <a href="/timesheet/update_by_super/{{data.id}}" data-bs-toggle="tooltip"
                                                data-bs-placement="top" title="Edit"><i
                                                    class="fa-solid fa-pen-to-square mr-1" style="color: blue;"></i></a>
                                        </td>

                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}